spring:

  #Database : PostgreSql
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hrms
    username: postgres
    password: 1234
    
     # JPA properties
 jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
 
#cloudinary       
cloudinary:
  cloud-name: aberimen
  api-key: <API_KEY>
  api-secret:  <API_SECRET>

    
    