export const ADD_TO_FAVORITE_JOB_SUCCESS = 'ADD_TO_FAVORITE_JOB_SUCCESS'
export const GET_FAVORITE_JOBS_SUCCESS = 'GET_FAVORITE_JOBS';
export const REMOVE_FROM_FAVORITE_JOBS_SUCCESS = 'REMOVE_FROM_FAVORITE_JOBS';


